name: "laravel_3dsecure"

services:
  nginx:
    container_name: laravel_3dsecure_nginx
    image: nginx:1.26
    ports:
      - 80:80
    volumes:
      - ./laravel:/var/www/html/laravel
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    container_name: laravel_3dsecure_php
    ports:
      - 5173:5173
    build: 
      context: .
      dockerfile: ./docker/php/dockerfile
    volumes:
      - ./laravel:/var/www/html/laravel
      - ./docker/php/www.conf:/etc/php-fpm.d/www.conf